//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happy.Scaffolding.MVC.UI {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MvcScaffolderDialogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MvcScaffolderDialogResources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Happy.Scaffolding.MVC.UI.MvcScaffolderDialogResources", typeof(MvcScaffolderDialogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 Add 的當地語系化字串。
        /// </summary>
        public static string AddButton_Content {
            get {
                return ResourceManager.GetString("AddButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Back 的當地語系化字串。
        /// </summary>
        public static string BackButton_Content {
            get {
                return ResourceManager.GetString("BackButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        public static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認後繼續 的當地語系化字串。
        /// </summary>
        public static string CheckBox_IsConfirm {
            get {
                return ResourceManager.GetString("CheckBox_IsConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Controller name 的當地語系化字串。
        /// </summary>
        public static string ControllerName {
            get {
                return ResourceManager.GetString("ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Data _context class: 的當地語系化字串。
        /// </summary>
        public static string DataContextTypeLabel_Content {
            get {
                return ResourceManager.GetString("DataContextTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Master page placeholder ID: 的當地語系化字串。
        /// </summary>
        public static string DesktopContentPlaceholderIdLabel_Content {
            get {
                return ResourceManager.GetString("DesktopContentPlaceholderIdLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Master page: 的當地語系化字串。
        /// </summary>
        public static string DesktopViewsLabel_Content {
            get {
                return ResourceManager.GetString("DesktopViewsLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a master page from the list 的當地語系化字串。
        /// </summary>
        public static string Error_DesktopMasterPageRequired {
            get {
                return ResourceManager.GetString("Error_DesktopMasterPageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please select a model class from the list 的當地語系化字串。
        /// </summary>
        public static string Error_ModelTypeRequired {
            get {
                return ResourceManager.GetString("Error_ModelTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please enter the ID of the placeholder control to place the generated content in 的當地語系化字串。
        /// </summary>
        public static string Error_PlaceholderIdRequired {
            get {
                return ResourceManager.GetString("Error_PlaceholderIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產生ViewModel 的當地語系化字串。
        /// </summary>
        public static string GenerateViews {
            get {
                return ResourceManager.GetString("GenerateViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (Leave empty if it is set in Razor _viewstart file) 的當地語系化字串。
        /// </summary>
        public static string LeaveEmpty {
            get {
                return ResourceManager.GetString("LeaveEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Method name / Store Procedure import function 的當地語系化字串。
        /// </summary>
        public static string MethodNameLabel_Content {
            get {
                return ResourceManager.GetString("MethodNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Model cla_ss: 的當地語系化字串。
        /// </summary>
        public static string ModelTypeLabel_Content {
            get {
                return ResourceManager.GetString("ModelTypeLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Next 的當地語系化字串。
        /// </summary>
        public static string NextButton_Content {
            get {
                return ResourceManager.GetString("NextButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 覆蓋已存在的檔案 的當地語系化字串。
        /// </summary>
        public static string OverwriteCheckBox_Content {
            get {
                return ResourceManager.GetString("OverwriteCheckBox_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Program title 的當地語系化字串。
        /// </summary>
        public static string ProgramerNameLabel_Content {
            get {
                return ResourceManager.GetString("ProgramerNameLabel_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Reference script libraries 的當地語系化字串。
        /// </summary>
        public static string ReferenceScriptLibraries {
            get {
                return ResourceManager.GetString("ReferenceScriptLibraries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add MVC from Store Procedure 的當地語系化字串。
        /// </summary>
        public static string SPScaffolderDialog_Title {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Query form setting 的當地語系化字串。
        /// </summary>
        public static string SPScaffolderDialog_Title2 {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Result list column setting 的當地語系化字串。
        /// </summary>
        public static string SPScaffolderDialog_Title3 {
            get {
                return ResourceManager.GetString("SPScaffolderDialog_Title3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add MVC controller and views for C.R.U.D 的當地語系化字串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use async controller actions 的當地語系化字串。
        /// </summary>
        public static string UseAsyncControllerActions {
            get {
                return ResourceManager.GetString("UseAsyncControllerActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Use a layout page 的當地語系化字串。
        /// </summary>
        public static string UseLayoutPage {
            get {
                return ResourceManager.GetString("UseLayoutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 View prefix 的當地語系化字串。
        /// </summary>
        public static string ViewPrefixLabel_Content {
            get {
                return ResourceManager.GetString("ViewPrefixLabel_Content", resourceCulture);
            }
        }
    }
}
