//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Happy.Scaffolding.MVC {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Happy.Scaffolding.MVC.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon Application {
            get {
                object obj = ResourceManager.GetObject("Application", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 Generates ASP.NET MVC controller and views for C.R.U.D (inserting, editing, deleting, and listing) from an Entity Framework data context. 的當地語系化字串。
        /// </summary>
        internal static string MVCScaffolder_Description {
            get {
                return ResourceManager.GetString("MVCScaffolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generates ASP.NET MVC controller and query/list view from an Entity Framework data context (method import from Store Procedure) . 的當地語系化字串。
        /// </summary>
        internal static string MVCScaffolder_Description2 {
            get {
                return ResourceManager.GetString("MVCScaffolder_Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HappyGen MVC 5 for C.R.U.D 的當地語系化字串。
        /// </summary>
        internal static string MVCScaffolder_Name {
            get {
                return ResourceManager.GetString("MVCScaffolder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 HappyGen MVC 5 for Search from EF6 (Store Procedure) 的當地語系化字串。
        /// </summary>
        internal static string MVCScaffolder_Name2 {
            get {
                return ResourceManager.GetString("MVCScaffolder_Name2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Add new data context... 的當地語系化字串。
        /// </summary>
        internal static string WebFormsCodeGeneratorViewModel_AddNewDbContext {
            get {
                return ResourceManager.GetString("WebFormsCodeGeneratorViewModel_AddNewDbContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Generates ASP.NET MVC controller and views for inserting, editing, deleting, and listing entities from an Entity Framework data context and model class. 的當地語系化字串。
        /// </summary>
        internal static string WebFormsScaffolder_Description {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ASP.NET MVC using Entity Framework 的當地語系化字串。
        /// </summary>
        internal static string WebFormsScaffolder_Name {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Unable to load the model type. If the project is not built, try building the project. 的當地語系化字串。
        /// </summary>
        internal static string WebFormsScaffolder_ProjectNotBuilt {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_ProjectNotBuilt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose a valid DbContext class. 的當地語系化字串。
        /// </summary>
        internal static string WebFormsScaffolder_SelectDbContextType {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_SelectDbContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Please choose a valid model class. 的當地語系化字串。
        /// </summary>
        internal static string WebFormsScaffolder_SelectModelType {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_SelectModelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ShowUIAndValidate needs to be called prior to this method. 的當地語系化字串。
        /// </summary>
        internal static string WebFormsScaffolder_ShowUIAndValidateNotCalled {
            get {
                return ResourceManager.GetString("WebFormsScaffolder_ShowUIAndValidateNotCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Action name cannot be null or empty. 的當地語系化字串。
        /// </summary>
        internal static string WebFormsViewScaffolder_EmptyActionName {
            get {
                return ResourceManager.GetString("WebFormsViewScaffolder_EmptyActionName", resourceCulture);
            }
        }
    }
}
